version: '3.9'

services:

  postgres:

    image: postgres:16

    container_name: postgres

    restart: always

    environment:

      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  booking-service:

    build: .

    container_name: booking-service

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres