apiVersion: v1
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db.cbe6s0ymsaw0.ap-south-1.rds.amazonaws.com:5432/bookingdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_PROFILES_ACTIVE: prod
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: booking:/ConfigMap:default/booking-config
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"SPRING_DATASOURCE_URL":"jdbc:postgresql://booking-db.cbe6s0ymsaw0.ap-south-1.rds.amazonaws.com:5432/bookingdb","SPRING_DATASOURCE_USERNAME":"postgres","SPRING_PROFILES_ACTIVE":"prod"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"booking:/ConfigMap:default/booking-config"},"name":"booking-config","namespace":"default"}}
  creationTimestamp: "2026-07-29T17:42:52Z"
  name: booking-config
  namespace: default
  resourceVersion: "30126"
  uid: 570c810d-004d-4b89-9e29-c2715397f71e
