apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: booking-project
  namespace: argocd

spec:

  description: Booking Microservices

  sourceRepos:
    - '*'

  destinations:
    - namespace: default
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'