apiVersion: v1
kind: Secret

metadata:
  name: github-repository
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:

  url: https://github.com/YOUR_USERNAME/PROMETHEUS-INTEGRATION.git

  username: YOUR_GITHUB_USERNAME

  password: YOUR_GITHUB_PAT