groups:

- name: booking-alerts

  rules:

  - alert: BookingServiceDown

    expr: up{job="booking-service"} == 0

    for: 1m

    labels:
      severity: critical

    annotations:
      summary: Booking Service Down

      description: Booking service is unreachable.

  - alert: HighCPUUsage

    expr: process_cpu_usage > 0.80

    for: 2m

    labels:
      severity: warning

    annotations:
      summary: High CPU Usage

      description: CPU usage exceeded 80%.

  - alert: HighMemoryUsage

    expr: jvm_memory_used_bytes / jvm_memory_max_bytes > 0.85

    for: 2m

    labels:
      severity: warning

    annotations:
      summary: High JVM Memory

      description: JVM memory usage exceeded 85%.