apiVersion: v1
kind: ConfigMap

metadata:
  name: booking-config

data:

  SPRING_PROFILES_ACTIVE: prod

  SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db.xxxxxxxxx.ap-south-1.rds.amazonaws.com:5432/bookingdb

  SPRING_DATASOURCE_USERNAME: postgres

  SERVER_PORT: "8080"