apiVersion: v1
kind: ConfigMap

metadata:
  name: booking-config

data:

  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile }}

  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl }}

  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername }}